version: '3.9'
services:
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-central-1
    ports:
      - 8001:8001
  localstack:
    image: localstack/localstack:3.0
    ports:
      - 4566:4566
